# Generated by Django 5.2.4 on 2025-09-02 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=200)),
                ('imo_number', models.CharField(max_length=10, unique=True)),
                ('ship_type', models.CharField(choices=[('Container Ship', 'Container Ship'), ('Cruise Ship', 'Cruise Ship'), ('Bulk Carrier', 'Bulk Carrier'), ('Tanker', 'Tanker'), ('Other', 'Other')], max_length=20)),
                ('flag_country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Maintenance', 'Under Maintenance'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='companies.company')),
                ('crew', models.ManyToManyField(blank=True, related_name='ships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ship_name'],
                'indexes': [models.Index(fields=['imo_number'], name='ships_ship_imo_num_d1857c_idx'), models.Index(fields=['company'], name='ships_ship_company_fffd69_idx')],
            },
        ),
    ]
