# Generated by Django 5.2.4 on 2025-08-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_userrank_rank'),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='ships', to='api.users'),
        ),
    ]
