# Generated by Django 6.0.3 on 2026-05-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_alter_company_company_flag"),
        ("ships", "0002_remove_ship_flag_country_ship_builder_ship_call_sign_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="builder",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ship",
            name="call_sign",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ship",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ships",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="ship",
            name="deadweight",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="in metric tons", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ship",
            name="engine_power_kw",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Engine Power (KW)"
            ),
        ),
        migrations.AlterField(
            model_name="ship",
            name="engine_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ship",
            name="gross_tonnage",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="ship",
            name="imo_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="ship",
            name="mmsi_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ship",
            name="official_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ship",
            name="port_of_registry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ship",
            name="ship_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ship",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Active", "Active"),
                    ("Under Maintenance", "Under Maintenance"),
                    ("Inactive", "Inactive"),
                ],
                default="Active",
                max_length=20,
                null=True,
            ),
        ),
    ]
