# Generated by Django 5.2.8 on 2025-12-27 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0021_contract_leave_pay_terms_contract_repatriation_terms_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline", models.CharField(max_length=100)),
                ("flight_number", models.CharField(max_length=50)),
                ("departure_airport", models.CharField(max_length=100)),
                ("arrival_airport", models.CharField(max_length=100)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "pnr",
                    models.CharField(
                        blank=True, help_text="Passenger Name Record", max_length=50
                    ),
                ),
                ("ticket_number", models.CharField(blank=True, max_length=50)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "ticket_file",
                    models.FileField(
                        blank=True, null=True, upload_to="flights/tickets/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Requested", "Requested"),
                            ("Booked", "Booked"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                        ],
                        default="Requested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights",
                        to="api.contract",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JoiningInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("port_agent_name", models.CharField(blank=True, max_length=255)),
                (
                    "port_agent_contact",
                    models.TextField(blank=True, help_text="Address, Phone, Email"),
                ),
                ("embarkation_port", models.CharField(max_length=100)),
                ("embarkation_date", models.DateField()),
                ("additional_guidelines", models.TextField(blank=True)),
                ("is_sent_to_crew", models.BooleanField(default=False)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joining_instructions",
                        to="api.contract",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joining_instructions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisaApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("Schengen", "Schengen"),
                            ("US C1/D", "US C1/D"),
                            ("Transit", "Transit"),
                            ("Arrival", "Arrival"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("Documents Collected", "Documents Collected"),
                            ("Submitted", "Submitted"),
                            ("Appointment Scheduled", "Appointment Scheduled"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Not Started",
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="visas/documents/"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.contract",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
