# Generated by Django 4.2.24 on 2025-09-28 18:47

import ai_document.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title or name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document', null=True)),
                ('file', models.FileField(help_text='Upload PDF or DOCX file', upload_to=ai_document.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('document_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document')], help_text='Type of document based on file extension', max_length=10)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Processing Completed'), ('failed', 'Processing Failed')], default='pending', help_text='Processing status of the document', max_length=20)),
                ('extracted_text', models.TextField(blank=True, help_text='Text content extracted from the document', null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Number of pages in the document', null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, help_text='Number of words in the document', null=True)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when document was uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when document was last updated')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EndpointStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=255, unique=True)),
                ('total_requests', models.PositiveIntegerField(default=0, help_text='Total number of requests')),
                ('successful_requests', models.PositiveIntegerField(default=0, help_text='Number of successful requests (2xx)')),
                ('error_requests', models.PositiveIntegerField(default=0, help_text='Number of error requests (4xx, 5xx)')),
                ('avg_processing_time_ms', models.FloatField(blank=True, help_text='Average processing time in milliseconds', null=True)),
                ('avg_response_size_bytes', models.FloatField(blank=True, help_text='Average response size in bytes', null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time this endpoint was accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the stats record was created')),
            ],
            options={
                'verbose_name': 'Endpoint Statistics',
                'verbose_name_plural': 'Endpoint Statistics',
                'ordering': ['-total_requests'],
            },
        ),
        migrations.CreateModel(
            name='SeafarerProfileSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seafarer_email', models.EmailField(help_text='Seafarer email address (unique identifier)', max_length=254, unique=True)),
                ('seafarer_name', models.CharField(help_text='Seafarer full name', max_length=200)),
                ('seafarer_nationality', models.CharField(blank=True, help_text='Seafarer nationality', max_length=100)),
                ('documents_processed', models.PositiveIntegerField(default=0, help_text='Number of documents processed for this seafarer')),
                ('avg_quality_score', models.FloatField(blank=True, help_text='Average quality score across all documents', null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='When this seafarer was first processed')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='When this seafarer was last processed')),
            ],
            options={
                'verbose_name': 'Seafarer Profile Summary',
                'verbose_name_plural': 'Seafarer Profile Summaries',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['seafarer_email'], name='ai_document_seafare_965822_idx'), models.Index(fields=['seafarer_nationality'], name='ai_document_seafare_c1dd06_idx'), models.Index(fields=['-last_seen'], name='ai_document_last_se_bc1f0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=255)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('status_code', models.IntegerField(help_text='HTTP status code')),
                ('response_data', models.JSONField(default=dict, help_text='JSON response data')),
                ('response_size_bytes', models.PositiveIntegerField(default=0, help_text='Response size in bytes')),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('document_id', models.CharField(blank=True, help_text='Document ID from the response', max_length=100, null=True)),
                ('seafarer_name', models.CharField(blank=True, help_text='Seafarer full name', max_length=200)),
                ('seafarer_email', models.EmailField(blank=True, help_text='Seafarer email address', max_length=254)),
                ('seafarer_nationality', models.CharField(blank=True, help_text='Seafarer nationality', max_length=100)),
                ('quality_score', models.FloatField(blank=True, help_text='Data quality score from response', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the log entry was created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Response Log',
                'verbose_name_plural': 'API Response Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', '-timestamp'], name='ai_document_endpoin_a0abd3_idx'), models.Index(fields=['user', '-timestamp'], name='ai_document_user_id_f00136_idx'), models.Index(fields=['status_code', '-timestamp'], name='ai_document_status__876e17_idx'), models.Index(fields=['seafarer_email'], name='ai_document_seafare_0e73ef_idx'), models.Index(fields=['document_id'], name='ai_document_documen_0bba3c_idx')],
            },
        ),
    ]
