# Generated by Django 4.2.24 on 2025-09-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_document', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
