# Generated by Django 4.2.24 on 2025-09-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_document', '0003_applicant_structured_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='structured_data',
        ),
    ]
