# Generated by Django 4.2.24 on 2025-10-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_document', '0005_applicant_assessments_applicant_competency_tests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applied_position_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
