# Generated by Django 5.2.8 on 2025-12-27 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0007_joborder_joborderposition"),
        ("ships", "0002_remove_ship_flag_country_ship_builder_ship_call_sign_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("MLC", "MLC 2006"),
                            ("ISO", "ISO 9001"),
                            ("PSC", "Port State Control"),
                            ("Internal", "Internal Audit"),
                            ("Client", "Client Audit"),
                        ],
                        max_length=50,
                    ),
                ),
                ("audit_date", models.DateField()),
                ("auditor_name", models.CharField(max_length=255)),
                (
                    "organization",
                    models.CharField(
                        help_text="e.g. DNV, Lloyd's, Flag State", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("In Progress", "In Progress"),
                            ("Passed", "Passed"),
                            (
                                "Authorized with Conditions",
                                "Authorized with Conditions",
                            ),
                            ("Failed", "Failed"),
                        ],
                        default="Scheduled",
                        max_length=50,
                    ),
                ),
                ("findings_count", models.PositiveIntegerField(default=0)),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance/audits/"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.company",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ships.ship",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("Accident", "Accident / Injury"),
                            ("Near Miss", "Near Miss"),
                            ("Grievance", "Crew Grievance / Complaint"),
                            ("Disciplinary", "Disciplinary Action"),
                            ("Pollution", "Pollution / Environmental"),
                            ("Security", "Security Breach"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        default="Low",
                        max_length=20,
                    ),
                ),
                ("date_occurred", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("immediate_action_taken", models.TextField(blank=True)),
                ("root_cause_analysis", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ships.ship",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
