# Generated by Django 5.2.8 on 2025-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vesseltype",
            name="name",
            field=models.CharField(
                choices=[
                    ("Container Ships", "Container Ships"),
                    ("Bulk Carriers", "Bulk Carriers"),
                    ("Tankers", "Tankers"),
                    ("Ro-Ro Ships", "Ro-Ro Ships"),
                    ("Passenger Ships", "Passenger Ships"),
                    ("Fishing Vessels", "Fishing Vessels"),
                    ("Recreational", "Recreational"),
                    ("Offshore Support Vessels", "Offshore Support Vessels"),
                    ("Icebreakers", "Icebreakers"),
                    ("Tugboats", "Tugboats"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
