# Generated by Django 6.0.3 on 2026-05-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_flag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Company Type",
                "verbose_name_plural": "Company Types",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="vesseltype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
