# Generated by Django 6.0.3 on 2026-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_companytype_alter_vesseltype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
