# Generated by Django 5.2.8 on 2025-11-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_delete_company_alter_financerecord_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financerecord",
            options={"ordering": ["-start_date"]},
        ),
        migrations.RenameField(
            model_name="financerecord",
            old_name="date",
            new_name="end_date",
        ),
        migrations.AlterUniqueTogether(
            name="financerecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="financerecord",
            name="start_date",
            field=models.DateField(default="2024-01-01"),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="financerecord",
            name="hours_worked",
        ),
        migrations.RemoveField(
            model_name="financerecord",
            name="ship",
        ),
    ]
