# Generated by Django 5.2.8 on 2025-12-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_alter_financerecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Overdue", "Overdue"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
