# Generated by Django 5.2.4 on 2025-09-02 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='flag_country',
        ),
        migrations.AddField(
            model_name='ship',
            name='builder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ship',
            name='call_sign',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ship',
            name='deadweight',
            field=models.PositiveIntegerField(default=0, help_text='in metric tons'),
        ),
        migrations.AddField(
            model_name='ship',
            name='engine_power_kw',
            field=models.PositiveIntegerField(default=0, verbose_name='Engine Power (KW)'),
        ),
        migrations.AddField(
            model_name='ship',
            name='engine_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ship',
            name='flag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ships', to='core.flag'),
        ),
        migrations.AddField(
            model_name='ship',
            name='gross_tonnage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='mmsi_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ship',
            name='official_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ship',
            name='port_of_registry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ship',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ships', to='core.vesseltype'),
        ),
    ]
