# Generated by Django 5.2.4 on 2025-09-02 20:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=780, unique=True)),
                ('name', models.CharField(max_length=780)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='YYYY-MM-DD format', null=True, verbose_name='Date of Birth')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married')], default='Single', max_length=40)),
                ('user_status', models.CharField(choices=[('VECATION', 'In Vecation'), ('ON_SITE', 'On Site'), ('MEDICAL VECATION', 'Medical')], default='On Site', max_length=40)),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('Place_Of_Birth', models.CharField(blank=True, max_length=100, null=True)),
                ('Nearest_Port', models.CharField(max_length=200, null=True)),
                ('Height_Cm', models.IntegerField(default=0)),
                ('Weight_Kg', models.IntegerField(default=0)),
                ('college_or_school', models.CharField(blank=True, max_length=200, null=True, verbose_name='College Or School')),
                ('marlins_test_issued_date', models.DateField(blank=True, null=True, verbose_name='Marlins Test Issued Date')),
                ('marlins_test_result', models.DecimalField(blank=True, decimal_places=2, help_text='Enter percentage score, e.g., 85.50', max_digits=5, null=True, verbose_name='Marlins Test Result (%)')),
                ('marlins_test_issued_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Marlins Test Issued By (Authority)')),
                ('marlins_test_issued_at', models.CharField(blank=True, max_length=150, null=True, verbose_name='Marlins Test Issued At (Location)')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('passport_issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_place_of_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('seaman_book_no', models.CharField(blank=True, max_length=50, null=True)),
                ('seaman_book_issue_date', models.DateField(blank=True, null=True)),
                ('seaman_book_expiry_date', models.DateField(blank=True, null=True)),
                ('seaman_book_issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('seaman_book_place_of_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('other_seaman_book_no', models.CharField(blank=True, max_length=50, null=True)),
                ('other_seaman_book_issue_date', models.DateField(blank=True, null=True)),
                ('other_seaman_book_expiry_date', models.DateField(blank=True, null=True)),
                ('other_seaman_book_issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('other_seaman_book_place_of_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('coc_certificate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('coc_certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('coc_issue_date', models.DateField(blank=True, null=True)),
                ('coc_expiry_date', models.DateField(blank=True, null=True)),
                ('coc_issued_by', models.CharField(default='EAMS', max_length=100)),
                ('coc_issued_at', models.CharField(default='Alex.', max_length=100)),
                ('goc_certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('goc_issue_date', models.DateField(blank=True, null=True)),
                ('goc_expiry_date', models.DateField(blank=True, null=True)),
                ('goc_issued_by', models.CharField(default='NTRA', max_length=100)),
                ('goc_issued_at', models.CharField(default='Cairo', max_length=100)),
                ('next_of_kin_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_address_country', models.CharField(blank=True, max_length=255, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('health_flag_state', models.CharField(blank=True, max_length=100, null=True)),
                ('health_number', models.CharField(blank=True, max_length=100, null=True)),
                ('health_issue_date', models.DateField(blank=True, null=True)),
                ('health_expiry_date', models.DateField(blank=True, null=True)),
                ('health_issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('health_issued_at', models.CharField(blank=True, max_length=255, null=True)),
                ('international_medical_number', models.CharField(blank=True, max_length=100, null=True)),
                ('international_medical_issue_date', models.DateField(blank=True, null=True)),
                ('international_medical_expiry_date', models.DateField(blank=True, null=True)),
                ('yellow_fever_number', models.CharField(blank=True, max_length=100, null=True)),
                ('yellow_fever_issue_date', models.DateField(blank=True, null=True)),
                ('yellow_fever_expiry_date', models.DateField(blank=True, null=True)),
                ('cholera_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cholera_issue_date', models.DateField(blank=True, null=True)),
                ('cholera_expiry_date', models.DateField(blank=True, null=True)),
                ('covid_vaccine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('covid_first_dose', models.DateField(blank=True, null=True)),
                ('covid_second_dose', models.DateField(blank=True, null=True)),
                ('covid_other_doses_or_remarks', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('certificates', models.ManyToManyField(blank=True, to='api.certificate')),
                ('codes', models.ManyToManyField(blank=True, to='api.rank')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_code', models.CharField(blank=True, max_length=20, null=True)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ranks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
