# Generated by Django 5.2.4 on 2025-09-02 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('ships', '0002_remove_ship_flag_country_ship_builder_ship_call_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='users',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='schengen_visa_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='us_visa_status',
            field=models.CharField(blank=True, help_text='e.g., B1/B2, C1/D, None', max_length=50),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_on_date', models.DateField()),
                ('sign_off_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.ForeignKey(help_text='The rank for this specific contract.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rank')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='ships.ship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sign_on_date'],
            },
        ),
    ]
