# Generated by Django 5.2.4 on 2025-08-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_delete_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Height_Cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='Nearest_Port',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Place_Of_Birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Weight_Kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
