# Generated by Django 5.2.4 on 2025-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_height_cm_users_nearest_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married')], default='Single', max_length=40),
        ),
    ]
