# Generated by Django 5.2.4 on 2025-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='marlins_test_issued_at',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Marlins Test Issued At (Location)'),
        ),
        migrations.AddField(
            model_name='users',
            name='marlins_test_issued_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Marlins Test Issued By (Authority)'),
        ),
        migrations.AddField(
            model_name='users',
            name='marlins_test_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Marlins Test Issued Date'),
        ),
        migrations.AddField(
            model_name='users',
            name='marlins_test_result',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter percentage score, e.g., 85.50', max_digits=5, null=True, verbose_name='Marlins Test Result (%)'),
        ),
    ]
