# Generated by Django 5.2.4 on 2025-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_users_marlins_test_issued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='College_School',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
