# Generated by Django 5.2.4 on 2025-08-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_users_college_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='College_School',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='College Or School'),
        ),
    ]
