# Generated by Django 5.2.4 on 2025-08-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_users_college_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='College_School',
        ),
        migrations.AddField(
            model_name='users',
            name='college_or_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='College Or School'),
        ),
    ]
