# Generated by Django 5.2.4 on 2025-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_users_other_seaman_book_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='coc_certificate_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='coc_certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='coc_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='coc_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='coc_issued_at',
            field=models.CharField(default='Alex.', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='coc_issued_by',
            field=models.CharField(default='EAMS', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='goc_certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='goc_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='goc_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='goc_issued_at',
            field=models.CharField(default='Cairo', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='goc_issued_by',
            field=models.CharField(default='NTRA', max_length=100),
        ),
    ]
