# Generated by Django 5.2.8 on 2025-11-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_users_marlins_test_issued_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="signed_file",
            field=models.FileField(
                blank=True, null=True, upload_to="contracts/signed/"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("HR Manager", "HR Manager"),
                    ("Recruiter", "Recruiter"),
                    ("Employee", "Employee"),
                ],
                default="Employee",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Signed", "Signed"),
                    ("Pending Signature", "Pending Signature"),
                    ("Draft", "Draft"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
