# Generated by Django 5.2.4 on 2025-08-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_users_coc_certificate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='next_of_kin_address_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='next_of_kin_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
