# Generated by Django 4.2.24 on 2025-12-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_company_contract_currency_alter_contract_rank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
