# Generated by Django 5.2.4 on 2025-08-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_users_cholera_expiry_date_users_cholera_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='certificates',
            field=models.TextField(blank=True, help_text='Select one or more certificates'),
        ),
    ]
