# Generated by Django 5.2.8 on 2025-12-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_users_options"),
        ("companies", "0004_alter_company_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_contracts",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="cvsubmission",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_cv_submissions",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_interviews",
                to="companies.company",
            ),
        ),
    ]
