# Generated by Django 5.2.4 on 2025-08-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_users_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='certificates',
        ),
    ]
