# Generated by Django 5.2.8 on 2025-12-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_cvsubmission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="user_status",
            field=models.CharField(
                choices=[
                    ("On Site", "On Site"),
                    ("Vacation", "Vacation"),
                    ("Medical Vacation", "Medical Vacation"),
                ],
                default="On Site",
                max_length=40,
            ),
        ),
    ]
