# Generated by Django 4.2.24 on 2025-12-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_users_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_status',
            field=models.CharField(choices=[('ON_SITE', 'ON_SITE'), ('VACATION', 'VACATION'), ('MEDICAL VACATION', 'MEDICAL VACATION')], default='On Site', max_length=40),
        ),
    ]
