# Generated by Django 5.2.4 on 2025-08-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_users_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='certificates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='users',
            name='codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
