# Generated by Django 4.2.24 on 2025-12-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_users_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
