# Generated by Django 5.2.8 on 2025-12-27 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_users_nationality_alter_users_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="leave_pay_terms",
            field=models.TextField(
                blank=True, help_text="Details on leave pay calculation", null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="repatriation_terms",
            field=models.TextField(
                blank=True, help_text="Terms regarding repatriation rights", null=True
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="blacklist_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BlacklistRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("date_added", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_blacklist_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceAppraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vessel_name", models.CharField(max_length=255)),
                ("appraisal_date", models.DateField()),
                (
                    "rating",
                    models.PositiveIntegerField(default=3, help_text="1 to 5 scale"),
                ),
                ("comments", models.TextField(blank=True)),
                ("evaluator_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appraisals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-appraisal_date"],
            },
        ),
    ]
