# Generated by Django 5.2.4 on 2025-08-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_users_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=780, unique=True)),
                ('name', models.CharField(max_length=780)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='codes',
        ),
        migrations.AddField(
            model_name='users',
            name='codes',
            field=models.ManyToManyField(blank=True, to='api.rank'),
        ),
    ]
