# Generated by Django 5.2.4 on 2025-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rank_remove_users_codes_users_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=780, unique=True)),
                ('name', models.CharField(max_length=780)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='certificates',
        ),
        migrations.AddField(
            model_name='users',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='api.certificates'),
        ),
    ]
