# Generated by Django 5.2.10 on 2026-01-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Email address", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name of the person", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Phone number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Master", "Master"),
                    ("1st. Officer – Chief Off.", "1st. Officer – Chief Off."),
                    ("2nd. Officer", "2nd. Officer"),
                    ("3rd. Officer", "3rd. Officer"),
                    ("Tug Master", "Tug Master"),
                    ("Boson", "Boson"),
                    ("A.B – O.S", "A.B – O.S"),
                    ("Steward / Galley Boy", "Steward / Galley Boy"),
                    (
                        "Cook / 2nd. Cook / Ass. Cook / Baker / Pastry",
                        "Cook / 2nd. Cook / Ass. Cook / Baker / Pastry",
                    ),
                    ("Carpenter", "Carpenter"),
                    ("Waiter", "Waiter"),
                    ("Purser", "Purser"),
                    ("Doctor", "Doctor"),
                    ("1st. Engineer", "1st. Engineer"),
                    ("2nd. Engineer", "2nd. Engineer"),
                    ("3rd. Engineer", "3rd. Engineer"),
                    (
                        "Electrical Engineer – E/E – ETO",
                        "Electrical Engineer – E/E – ETO",
                    ),
                    ("Assistant Electrician", "Assistant Electrician"),
                    ("4th. Engineer", "4th. Engineer"),
                    ("Electrician", "Electrician"),
                    ("Motor Man / Mechanic", "Motor Man / Mechanic"),
                    ("Oiler", "Oiler"),
                    ("Fitter – Welder", "Fitter – Welder"),
                    ("Wiper", "Wiper"),
                    ("Other", "Other"),
                ],
                help_text="Position/Rank",
                max_length=100,
                null=True,
            ),
        ),
    ]
