# Generated by Django 5.2.4 on 2025-08-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_certificates_remove_users_certificates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
        migrations.AlterField(
            model_name='users',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='api.certificate'),
        ),
    ]
