# Generated by Django 5.2.10 on 2026-01-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_document_email_document_name_document_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Active", "Active"),
                    ("Blacklist", "Blacklist"),
                ],
                default="Pending",
                help_text="Document status",
                max_length=20,
            ),
        ),
    ]
