# Generated by Django 5.2.10 on 2026-01-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_document_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="generated_id",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated 12-digit ID",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
    ]
