# Generated by Django 5.2.10 on 2026-01-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_users_generated_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Synced from Document file",
                null=True,
                upload_to="user_files/",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="Synced from Document position",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Synced from Document title",
                max_length=255,
                null=True,
            ),
        ),
    ]
