# Generated by Django 5.2.4 on 2025-08-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_users_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_status',
            field=models.CharField(choices=[('VECATION', 'In Vecation'), ('ON_SITE', 'On Site'), ('MEDICAL VECATION', 'Medical')], default='On Site', max_length=40),
        ),
    ]
