# Generated by Django 5.2.10 on 2026-01-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_users_file_users_position_users_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ces_test_issued_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='ces_test_issued_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='ces_test_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='ces_test_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
