# Generated by Django 5.2.4 on 2025-08-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_users_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_code', models.CharField(max_length=780, unique=True)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ranks', to='api.users')),
            ],
        ),
    ]
