# Generated by Django 6.0.1 on 2026-01-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_users_file_users_position_users_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True, help_text='Last time user data was updated'),
        ),
        migrations.AddField(
            model_name='users',
            name='register_code',
            field=models.CharField(blank=True, help_text='Registration code from system or document', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='register_date',
            field=models.DateField(blank=True, help_text='User registration date', null=True),
        ),
    ]
