# Generated by Django 5.2.10 on 2026-01-17 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_users_ces_test_issued_at_users_ces_test_issued_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('general_remarks', models.TextField(blank=True, null=True)),
                ('speaking_level', models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Native', 'Native')], max_length=50, null=True)),
                ('writing_level', models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Native', 'Native')], max_length=50, null=True)),
                ('reading_level', models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Native', 'Native')], max_length=50, null=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True)),
                ('cefr_description', models.TextField(blank=True, help_text='Description of selected CEFR Level', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='languages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
