# Generated by Django 6.0.1 on 2026-01-30 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_users_last_updated_date_users_register_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('general_marks', models.IntegerField(default=0)),
                ('speaking', models.IntegerField(default=0)),
                ('writing', models.IntegerField(default=0)),
                ('reading', models.IntegerField(default=0)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], default='A1', max_length=2)),
                ('cefr_description', models.TextField(blank=True, help_text='Detailed description of the language ability based on CEFR', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Language Proficiency',
                'verbose_name_plural': 'Language Proficiencies',
            },
        ),
    ]
