# Generated by Django 5.2.4 on 2025-08-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_userrank_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='assigned_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rank'),
        ),
    ]
