# Generated by Django 6.0.1 on 2026-01-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_languageproficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
