# Generated by Django 5.2.10 on 2026-01-17 21:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_userlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[("BAHAMAS SEAMAN'S BOOK", "BAHAMAS SEAMAN'S BOOK"), ("BELIZE SEAMAN'S BOOK", "BELIZE SEAMAN'S BOOK"), ("BERMUDA SEAMAN'S BOOK", "BERMUDA SEAMAN'S BOOK"), ('EU national ID', 'EU national ID'), ('Exit Interview', 'Exit Interview'), ("LIBERIAN SEAMAN'S BOOK", "LIBERIAN SEAMAN'S BOOK"), ('Local ID Card', 'Local ID Card'), ("LUXEMBOURG SEAMAN'S BOOK", "LUXEMBOURG SEAMAN'S BOOK"), ("PALAU SEAMAN'S BOOK", "PALAU SEAMAN'S BOOK"), ("PANAMA SEAMAN'S BOOK", "PANAMA SEAMAN'S BOOK"), ('Passport', 'Passport'), ('PERMESSO SOGGIORNO PERMANENTE', 'PERMESSO SOGGIORNO PERMANENTE'), ('PERMESSO SOGGIORNO TEMPORANEO', 'PERMESSO SOGGIORNO TEMPORANEO'), ('Personal Record Sheet', 'Personal Record Sheet'), ('RESIDENCE CERTIFICATE', 'RESIDENCE CERTIFICATE'), ("SEAFARERS' ID. DOC. ILO 185", "SEAFARERS' ID. DOC. ILO 185"), ("Seaman's Book", "Seaman's Book"), ("Seaman's Book/Card or ID", "Seaman's Book/Card or ID"), ("U.K. SEAMAN'S BOOK", "U.K. SEAMAN'S BOOK")], max_length=100)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='personal_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
