# Generated by Django 6.0.1 on 2026-02-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_personaldocument"),
        ("api", "0029_users_city_users_country"),
    ]

    operations = []
