# Generated by Django 5.2.4 on 2025-08-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_userrank_assigned_code_alter_userrank_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='assigned_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ranks', to='api.rank'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
