# Generated by Django 5.2.4 on 2025-08-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_userrank_assigned_code_alter_userrank_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
