# Generated by Django 6.0.1 on 2026-02-02 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_merge_20260202_2046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlanguage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_languages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
