# Generated by Django 6.0.1 on 2026-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_userlanguage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageproficiency',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Italian', 'Italian'), ('Portuguese', 'Portuguese'), ('Dutch', 'Dutch'), ('Russian', 'Russian'), ('Chinese (Mandarin)', 'Chinese (Mandarin)'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Arabic', 'Arabic'), ('Hindi', 'Hindi'), ('Greek', 'Greek'), ('Polish', 'Polish'), ('Turkish', 'Turkish'), ('Swedish', 'Swedish'), ('Norwegian', 'Norwegian'), ('Danish', 'Danish'), ('Finnish', 'Finnish'), ('Czech', 'Czech'), ('Romanian', 'Romanian'), ('Ukrainian', 'Ukrainian'), ('Thai', 'Thai'), ('Vietnamese', 'Vietnamese'), ('Indonesian', 'Indonesian'), ('Malay', 'Malay'), ('Tagalog', 'Tagalog'), ('Other', 'Other')], max_length=100),
        ),
    ]
