# Generated by Django 6.0.1 on 2026-02-16 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_languageproficiency_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Declaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_disease",
                    models.BooleanField(
                        default=False,
                        help_text="Did you suffer, or presently suffer from, any disease likely to render you unfit for sea service?",
                    ),
                ),
                (
                    "disease_details",
                    models.TextField(
                        blank=True,
                        help_text="If yes, please provide details about the disease",
                        null=True,
                    ),
                ),
                (
                    "has_accident",
                    models.BooleanField(
                        default=False,
                        help_text="Did you suffer any accident which rendered you temporary and/or partially disabled?",
                    ),
                ),
                (
                    "accident_details",
                    models.TextField(
                        blank=True,
                        help_text="If yes, please provide details about the accident",
                        null=True,
                    ),
                ),
                (
                    "has_psychiatric_treatment",
                    models.BooleanField(
                        default=False,
                        help_text="Did you ever undergo psychiatric treatment?",
                    ),
                ),
                (
                    "psychiatric_treatment_details",
                    models.TextField(
                        blank=True,
                        help_text="If yes, please provide details about the psychiatric treatment",
                        null=True,
                    ),
                ),
                (
                    "has_addiction",
                    models.BooleanField(
                        default=False,
                        help_text="Are you addicted to alcohol or drugs of any kind?",
                    ),
                ),
                (
                    "addiction_details",
                    models.TextField(
                        blank=True,
                        help_text="If yes, please provide details about the addiction",
                        null=True,
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has given consent for data processing",
                    ),
                ),
                (
                    "declaration_place",
                    models.CharField(
                        blank=True,
                        help_text="Location where declaration was signed",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "declaration_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when declaration was signed",
                        null=True,
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="Digital signature or signature reference",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User making the declaration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Declaration",
                "verbose_name_plural": "Declarations",
                "ordering": ["-created_at"],
            },
        ),
    ]
