# Generated by Django 6.0.1 on 2026-02-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_declaration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seaservice",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="seaservice",
            name="dwt_grt",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="seaservice",
            name="engine_type_bh_kw",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="seaservice",
            name="flag",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="seaservice",
            name="period",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="seaservice",
            name="rank",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="seaservice",
            name="reason_for_sign_off",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="seaservice",
            name="signed_off",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seaservice",
            name="signed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seaservice",
            name="vessel_name_imo",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="seaservice",
            name="vessel_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
