# Generated by Django 6.0.1 on 2026-02-20 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_sea_service_optional_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="NextOfKin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Brother", "Brother"),
                            ("Sister", "Sister"),
                            ("Wife", "Wife"),
                            ("Husband", "Husband"),
                            ("Son", "Son"),
                            ("Daughter", "Daughter"),
                            ("Uncle", "Uncle"),
                            ("Aunt", "Aunt"),
                            ("Friend", "Friend"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "address_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_of_kins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Next of Kin",
                "verbose_name_plural": "Next of Kin",
                "ordering": ["-created_at"],
            },
        ),
    ]
