# Generated by Django 6.0.1 on 2026-02-20 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_nextofkin"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldocument",
            name="place_of_issue",
            field=models.CharField(
                blank=True,
                help_text="City or office where the document was issued",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personaldocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="personal_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "docx", "doc", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
