# Generated by Django 6.0.1 on 2026-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_passport_seamanbook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seamanbook",
            name="user",
        ),
        migrations.AddField(
            model_name="personaldocument",
            name="issued_by",
            field=models.CharField(
                blank=True,
                help_text="Authority or entity that issued the document",
                max_length=255,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Passport",
        ),
        migrations.DeleteModel(
            name="SeamanBook",
        ),
    ]
