# Generated by Django 6.0.1 on 2026-02-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_remove_seamanbook_user_personaldocument_issued_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seaservice",
            name="bh",
            field=models.CharField(
                blank=True, default="", help_text="Brake Horsepower", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="seaservice",
            name="dwt",
            field=models.CharField(
                blank=True, default="", help_text="Deadweight Tonnage", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="seaservice",
            name="engine_type",
            field=models.CharField(
                blank=True, default="", help_text="Engine Type", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="seaservice",
            name="gwt",
            field=models.CharField(
                blank=True, default="", help_text="Gross Weight Tonnage", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="seaservice",
            name="kw",
            field=models.CharField(
                blank=True, default="", help_text="Kilowatts", max_length=100
            ),
        ),
    ]
