# Generated by Django 6.0.1 on 2026-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_seaservice_bh_seaservice_dwt_seaservice_engine_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="application_for_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Master", "Master"),
                    ("1st. Officer – Chief Off.", "1st. Officer – Chief Off."),
                    ("2nd. Officer", "2nd. Officer"),
                    ("3rd. Officer", "3rd. Officer"),
                    ("Tug Master", "Tug Master"),
                    ("Boson", "Boson"),
                    ("A.B – O.S", "A.B – O.S"),
                    ("Steward / Galley Boy", "Steward / Galley Boy"),
                    (
                        "Cook / 2nd. Cook / Ass. Cook / Baker / Pastry",
                        "Cook / 2nd. Cook / Ass. Cook / Baker / Pastry",
                    ),
                    ("Carpenter", "Carpenter"),
                    ("Waiter", "Waiter"),
                    ("Purser", "Purser"),
                    ("Doctor", "Doctor"),
                    ("1st. Engineer", "1st. Engineer"),
                    ("2nd. Engineer", "2nd. Engineer"),
                    ("3rd. Engineer", "3rd. Engineer"),
                    (
                        "Electrical Engineer – E/E – ETO",
                        "Electrical Engineer – E/E – ETO",
                    ),
                    ("Assistant Electrician", "Assistant Electrician"),
                    ("4th. Engineer", "4th. Engineer"),
                    ("Electrician", "Electrician"),
                    ("Motor Man / Mechanic", "Motor Man / Mechanic"),
                    ("Oiler", "Oiler"),
                    ("Fitter – Welder", "Fitter – Welder"),
                    ("Wiper", "Wiper"),
                    ("Other", "Other"),
                ],
                help_text="Application for position",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="available_date",
            field=models.DateField(
                blank=True, help_text="Date of availability", null=True
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="other_position",
            field=models.CharField(
                blank=True,
                help_text="Other position if not in the list",
                max_length=255,
                null=True,
            ),
        ),
    ]
