# Generated by Django 6.0.1 on 2026-02-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_users_application_for_position_users_available_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seaservice",
            name="imo_number",
            field=models.CharField(
                blank=True, default="", help_text="IMO Number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="seaservice",
            name="vessel_name",
            field=models.CharField(
                blank=True, default="", help_text="Vessel Name", max_length=255
            ),
        ),
    ]
