# Generated by Django 6.0.1 on 2026-02-21 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_seaservice_imo_number_seaservice_vessel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="seaservice",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="sea_services/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "docx", "doc", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
