# Generated by Django 6.0.1 on 2026-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_seaservice_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seaservice",
            name="dwt_grt",
        ),
        migrations.RemoveField(
            model_name="seaservice",
            name="engine_type_bh_kw",
        ),
        migrations.RemoveField(
            model_name="seaservice",
            name="gwt",
        ),
        migrations.AddField(
            model_name="seaservice",
            name="grt",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Gross Register Tonnage",
                max_length=100,
            ),
        ),
    ]
