# Generated by Django 6.0.1 on 2026-02-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_remove_seaservice_dwt_grt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="languageproficiency",
            name="reading",
        ),
        migrations.RemoveField(
            model_name="languageproficiency",
            name="speaking",
        ),
        migrations.RemoveField(
            model_name="languageproficiency",
            name="writing",
        ),
        migrations.AddField(
            model_name="languageproficiency",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="languages/"),
        ),
        migrations.AddField(
            model_name="languageproficiency",
            name="reading_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Elementary", "Elementary"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Native", "Native"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="languageproficiency",
            name="speaking_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Elementary", "Elementary"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Native", "Native"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="languageproficiency",
            name="writing_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Elementary", "Elementary"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Native", "Native"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
