# Generated by Django 6.0.1 on 2026-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_remove_languageproficiency_reading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="ces_test_attachment",
            field=models.FileField(blank=True, null=True, upload_to="ces_tests/"),
        ),
        migrations.AddField(
            model_name="users",
            name="marlins_test_attachment",
            field=models.FileField(blank=True, null=True, upload_to="marlins_tests/"),
        ),
    ]
