# Generated by Django 6.0.1 on 2026-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_users_ces_test_attachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nextofkin",
            name="phone2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="next_of_kin_phone2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
