# Generated by Django 6.0.1 on 2026-03-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_nextofkin_phone2_users_next_of_kin_phone2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="salary",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
