# Generated by Django 6.0.1 on 2026-03-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_alter_users_coc_certificate_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="other_seaman_book_attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="other_seaman_books/"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="passport_attachment",
            field=models.FileField(blank=True, null=True, upload_to="passports/"),
        ),
        migrations.AddField(
            model_name="users",
            name="seaman_book_attachment",
            field=models.FileField(blank=True, null=True, upload_to="seaman_books/"),
        ),
    ]
