# Generated by Django 6.0.1 on 2026-03-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_users_other_seaman_book_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Bahamas Seaman's Book", "Bahamas Seaman's Book"),
                    ("Belize Seaman's Book", "Belize Seaman's Book"),
                    ("Bermuda Seaman's Book", "Bermuda Seaman's Book"),
                    ("Eu National Id", "Eu National Id"),
                    ("Exit Interview", "Exit Interview"),
                    ("Liberian Seaman's Book", "Liberian Seaman's Book"),
                    ("Local Id Card", "Local Id Card"),
                    ("Luxembourg Seaman's Book", "Luxembourg Seaman's Book"),
                    ("Palau Seaman's Book", "Palau Seaman's Book"),
                    ("Panama Seaman's Book", "Panama Seaman's Book"),
                    ("Passport", "Passport"),
                    ("Permesso Soggiorno Permanente", "Permesso Soggiorno Permanente"),
                    ("Permesso Soggiorno Temporaneo", "Permesso Soggiorno Temporaneo"),
                    ("Personal Record Sheet", "Personal Record Sheet"),
                    ("Residence Certificate", "Residence Certificate"),
                    ("Seafarers' Id. Doc. Ilo 185", "Seafarers' Id. Doc. Ilo 185"),
                    ("Seaman's Book", "Seaman's Book"),
                    ("Seaman's Book/Card Or Id", "Seaman's Book/Card Or Id"),
                    ("U.K. Seaman's Book", "U.K. Seaman's Book"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="coc_certificate_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Master", "Master"),
                    ("Chief Mate", "Chief Mate"),
                    ("2nd Officer", "2nd Officer"),
                    ("3rd Officer", "3rd Officer"),
                    ("Marine Chief Eng.", "Marine Chief Eng."),
                    ("2nd Marine Eng.", "2nd Marine Eng."),
                    ("3rd Marine Eng.", "3rd Marine Eng."),
                    ("Electro-Technical Officer", "Electro-Technical Officer"),
                    ("Gmdss General Operator", "Gmdss General Operator"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
