# Generated by Django 6.0.1 on 2026-03-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_alter_personaldocument_document_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="coc_certificate_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Master", "Master"),
                    ("Chief Mate", "Chief Mate"),
                    ("Chief Officer", "Chief Officer"),
                    ("2nd Officer", "2nd Officer"),
                    ("3rd Officer", "3rd Officer"),
                    ("Marine Chief Eng.", "Marine Chief Eng."),
                    ("2nd Marine Eng.", "2nd Marine Eng."),
                    ("3rd Marine Eng.", "3rd Marine Eng."),
                    ("Electro-Technical Officer", "Electro-Technical Officer"),
                    ("Gmdss General Operator", "Gmdss General Operator"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
