# Generated by Django 6.0.1 on 2026-03-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_alter_users_coc_certificate_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seaservice",
            options={"ordering": ["-signed_on"]},
        ),
    ]
