# Generated by Django 6.0.3 on 2026-03-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_alter_seaservice_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="Height_Cm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="Weight_Kg",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
