# Generated by Django 6.0.3 on 2026-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_alter_users_height_cm_alter_users_weight_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="overall_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("XXXL", "XXXL"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="shirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("XXXL", "XXXL"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
