# Generated by Django 6.0.3 on 2026-04-27 19:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_alter_users_overall_size_alter_users_shirt_size"),
        ("companies", "0008_company_company_flag_company_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "docx"]
                    )
                ],
            ),
        ),
    ]
