# Generated by Django 6.0.3 on 2026-05-01 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_document_company_alter_document_file"),
        ("companies", "0008_company_company_flag_company_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="job_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="companies.joborderposition",
            ),
        ),
        migrations.AddField(
            model_name="cvsubmission",
            name="job_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cv_submissions",
                to="companies.joborderposition",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="job_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="companies.joborderposition",
            ),
        ),
    ]
