# Generated by Django 6.0.3 on 2026-05-05 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_contract_job_position_cvsubmission_job_position_and_more"),
        ("ships", "0002_remove_ship_flag_country_ship_builder_ship_call_sign_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="ship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="ships.ship",
            ),
        ),
    ]
