# Generated by Django 6.0.3 on 2026-05-05 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_contract_ship_nullable"),
        ("ships", "0002_remove_ship_flag_country_ship_builder_ship_call_sign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvsubmission",
            name="ship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cv_submissions",
                to="ships.ship",
            ),
        ),
    ]
