# Generated by Django 6.0.3 on 2026-05-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_cvsubmission_ship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="position",
            field=models.CharField(
                blank=True, help_text="Position/Rank", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="application_for_position",
            field=models.CharField(
                blank=True,
                help_text="Application for position",
                max_length=100,
                null=True,
            ),
        ),
    ]
