# Generated by Django 6.0.3 on 2026-05-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_alter_document_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="position_id",
            field=models.IntegerField(
                blank=True,
                help_text="Position ID from frontend or Rank table",
                null=True,
            ),
        ),
    ]
