# Generated by Django 6.0.3 on 2026-05-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_company_contact_phone_company_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Australian Visa Crew", "Australian Visa Crew"),
                    ("Bahamas Seaman's Book", "Bahamas Seaman's Book"),
                    ("Belize Seaman's Book", "Belize Seaman's Book"),
                    ("Bermuda Seaman's Book", "Bermuda Seaman's Book"),
                    ("Brazil", "Brazil"),
                    ("China", "China"),
                    ("Cyprus", "Cyprus"),
                    ("Eu National Id", "Eu National Id"),
                    ("Exit Interview", "Exit Interview"),
                    ("Germany Visa D", "Germany Visa D"),
                    ("Italian Visa D", "Italian Visa D"),
                    ("Liberian Seaman's Book", "Liberian Seaman's Book"),
                    ("Local Id Card", "Local Id Card"),
                    ("Luxembourg Seaman's Book", "Luxembourg Seaman's Book"),
                    ("Palau Seaman's Book", "Palau Seaman's Book"),
                    ("Panama Seaman's Book", "Panama Seaman's Book"),
                    ("Passport", "Passport"),
                    ("Permesso Soggiorno Permanente", "Permesso Soggiorno Permanente"),
                    ("Permesso Soggiorno Temporaneo", "Permesso Soggiorno Temporaneo"),
                    ("Personal Record Sheet", "Personal Record Sheet"),
                    ("Residence Certificate", "Residence Certificate"),
                    ("Saudi Arabia", "Saudi Arabia"),
                    ("Schengen Visa", "Schengen Visa"),
                    ("Seafarers' Id. Doc. Ilo 185", "Seafarers' Id. Doc. Ilo 185"),
                    ("Seaman's Book", "Seaman's Book"),
                    ("Seaman's Book/Card Or Id", "Seaman's Book/Card Or Id"),
                    ("Turkey", "Turkey"),
                    ("U.K. Seaman's Book", "U.K. Seaman's Book"),
                    ("UAE", "UAE"),
                    ("US Visa B1/B2", "US Visa B1/B2"),
                    ("US Visa C1/D", "US Visa C1/D"),
                ],
                max_length=100,
            ),
        ),
    ]
