# Generated by Django 6.0.6 on 2026-07-27
#
# Backfill reviewed_date for CVSubmissions that already have a
# reviewed_by but no reviewed_date. The model allows both fields to
# be set independently, but the frontend treats them as a pair
# (Reviewed By + Reviewed Date columns), so existing rows that were
# reviewed via the old PATCH path showed a '-' date even though
# they were already reviewed.
#
# Going forward, perform_update on CVSubmissionViewSet will
# auto-stamp reviewed_date whenever reviewed_by is set, so this
# backfill is a one-shot cleanup for legacy rows.

from django.db import migrations
from django.utils import timezone


def backfill_reviewed_date(apps, schema_editor):
    CVSubmission = apps.get_model("api", "CVSubmission")
    now = timezone.now()
    updated = CVSubmission.objects.filter(
        reviewed_by__isnull=False,
        reviewed_date__isnull=True,
    ).update(reviewed_date=now)
    if updated:
        print(f"  [backfill] reviewed_date set on {updated} CV submission(s)")


def noop_reverse(apps, schema_editor):
    # No reverse — we don't want to wipe reviewed_date on rollback,
    # because the new perform_update will keep stamping it forward.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_alter_users_role"),
    ]

    operations = [
        migrations.RunPython(backfill_reviewed_date, noop_reverse),
    ]
