# Generated by Django 6.0.6 on 2026-08-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_backfill_reviewed_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Contract duration in months (e.g. 6, 9, 12). May be derived from sign_on_date / sign_off_date if not set explicitly.",
                null=True,
            ),
        ),
    ]
