# Generated by Django 6.0.6 on 2026-08-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_contract_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="languageproficiency",
            old_name="general_marks",
            new_name="general_remarks",
        ),
    ]
