# Generated by Django 6.0.6 on 2026-08-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_document_contract_alter_document_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="user_status",
            field=models.CharField(
                choices=[
                    ("ON_SITE", "ON_SITE"),
                    ("ON_BOARD", "ON BOARD"),
                    ("VACATION", "VACATION"),
                    ("MEDICAL_VACATION", "MEDICAL VACATION"),
                    ("NEW_APPLICANT", "NEW APPLICANT"),
                ],
                default="ON_SITE",
                max_length=40,
            ),
        ),
    ]
