# Generated by Django 6.0.6 on 2026-08-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_alter_users_user_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="otp_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
