# Generated by Django 6.0.6 on 2026-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_add_phone_verification_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="welcome_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
