# Generated by Django 6.0.6 on 2026-09-06 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_users_welcome_email_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional human-readable title. If empty, the file name is used.",
                        max_length=200,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded file (PDF / DOCX / image).",
                        upload_to="admin_attachments/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cv_submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional CV submission this attachment was created against.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_attachments",
                        to="api.cvsubmission",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin user who uploaded this file.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_attachments_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The seafarer this admin attachment belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="api_adminat_user_id_bbc4df_idx",
                    ),
                    models.Index(
                        fields=["cv_submission"], name="api_adminat_cv_subm_bf39a2_idx"
                    ),
                ],
            },
        ),
    ]
