# Generated by Django 6.0.6 on 2026-09-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_adminattachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personaldocument",
            options={"ordering": ["document_type"]},
        ),
        migrations.AlterUniqueTogether(
            name="personaldocument",
            unique_together={("user", "document_type")},
        ),
    ]
