# Generated by Django 6.0.6 on 2026-09-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_personaldocument_unique_per_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seaservice",
            options={"ordering": ["signed_on", "id"]},
        ),
    ]
