# Generated by Django 5.1.4 on 2026-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_add_nationality_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="cholera_no_expiry",
            field=models.BooleanField(
                default=False,
                help_text="True when the certificate has no expiry (e.g. 'Valid for life long').",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="international_medical_no_expiry",
            field=models.BooleanField(
                default=False,
                help_text="True when the certificate has no expiry (e.g. 'Valid for life long').",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="yellow_fever_no_expiry",
            field=models.BooleanField(
                default=False,
                help_text="True when the certificate has no expiry (e.g. 'Valid for life long').",
            ),
        ),
    ]
