# Generated by Django 4.2.24 on 2025-09-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='raw_text',
            field=models.TextField(blank=True, help_text='The raw text extracted from the document.'),
        ),
    ]
