# Generated by Django 4.2.24 on 2025-09-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_parser', '0002_parseddocument_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='extracted_features_json',
            field=models.TextField(blank=True, default='{}', help_text='The extracted seafarer features stored as JSON string.'),
        ),
        migrations.AddField(
            model_name='parseddocument',
            name='processing_metadata_json',
            field=models.TextField(blank=True, default='{}', help_text='Metadata about the processing including extraction quality, tables found, etc.'),
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('step', models.CharField(help_text="Processing step (e.g., 'extraction', 'ai_processing', 'validation')", max_length=100)),
                ('extra_data_json', models.TextField(blank=True, default='{}', help_text='Additional structured data related to this log entry as JSON string')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='doc_parser.parseddocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personal', 'Personal Information'), ('qualification', 'Qualification'), ('experience', 'Experience'), ('medical', 'Medical Information'), ('contact', 'Contact Information'), ('document', 'Document Information'), ('other', 'Other')], max_length=20)),
                ('field_name', models.CharField(help_text='Name of the extracted field', max_length=100)),
                ('field_value', models.TextField(help_text='Value of the extracted field')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score of the extraction (0.0 to 1.0)')),
                ('extraction_method', models.CharField(default='ai_extraction', help_text='Method used to extract this feature', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='doc_parser.parseddocument')),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'field_name'], name='doc_parser__categor_3d9ffb_idx'), models.Index(fields=['document', 'category'], name='doc_parser__documen_fc8039_idx')],
                'unique_together': {('document', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_index', models.IntegerField(help_text='Index of the table in the document')),
                ('table_data_json', models.TextField(help_text='Table data as JSON string')),
                ('table_headers_json', models.TextField(blank=True, default='[]', help_text='Table headers as JSON string')),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='doc_parser.parseddocument')),
            ],
            options={
                'unique_together': {('document', 'table_index')},
            },
        ),
    ]
