# Generated by Django 4.2.23 on 2025-10-24 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_remove_ship_flag_country_ship_builder_ship_call_sign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterModelOptions(
            name='financerecord',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='financerecord',
            old_name='end_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='financerecord',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours worked (0 - 24)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='ships.ship'),
        ),
        migrations.AlterUniqueTogether(
            name='financerecord',
            unique_together={('user', 'ship', 'date')},
        ),
        migrations.RemoveField(
            model_name='financerecord',
            name='start_date',
        ),
    ]
