# Generated by Django 6.0.3 on 2026-03-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
