# Generated by Django 6.0.3 on 2026-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_expiry_date_alter_course_issue_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="country_of_issue",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="issued_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="issued_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
