# Generated by Django 5.2.8 on 2025-12-08 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_alter_company_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["company_name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
