# Generated by Django 5.2.8 on 2025-12-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_alter_company_company_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("Shipping Manning Companies", "Shipping Manning Companies"),
                    ("Cargo Manning Companies", "Cargo Manning Companies"),
                    (
                        "Cruise & Hospitality Manning Companies",
                        "Cruise & Hospitality Manning Companies",
                    ),
                    (
                        "Offshore & Oil/Gas Manning Companies",
                        "Offshore & Oil/Gas Manning Companies",
                    ),
                    (
                        "Fishing Fleet Manning Companies",
                        "Fishing Fleet Manning Companies",
                    ),
                    (
                        "General Crew Manning Companies",
                        "General Crew Manning Companies",
                    ),
                    (
                        "Specialized Marine Manning Companies",
                        "Specialized Marine Manning Companies",
                    ),
                    (
                        "Temporary / Contract Manning Agencies",
                        "Temporary / Contract Manning Agencies",
                    ),
                    (
                        "Full Crew Management Companies",
                        "Full Crew Management Companies",
                    ),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
