# Generated by Django 5.2.8 on 2025-12-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_contract_leave_pay_terms_contract_repatriation_terms_and_more"),
        ("companies", "0006_alter_company_company_type"),
        ("ships", "0002_remove_ship_flag_country_ship_builder_ship_call_sign_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="e.g. JO-2024-001", max_length=50, unique=True
                    ),
                ),
                ("request_date", models.DateField()),
                ("target_joining_date", models.DateField()),
                (
                    "vessel_type_override",
                    models.CharField(
                        blank=True,
                        help_text="Override if different from ship's default",
                        max_length=100,
                    ),
                ),
                ("trading_area", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending Review"),
                            ("Open", "Open / Sourcing"),
                            ("In Progress", "In Progress / Interviewing"),
                            ("Fulfilled", "Fulfilled"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_orders",
                        to="companies.company",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_orders",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="JobOrderPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("contract_duration_months", models.PositiveIntegerField(default=6)),
                ("remarks", models.TextField(blank=True)),
                (
                    "job_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="companies.joborder",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.rank",
                    ),
                ),
            ],
        ),
    ]
