# Generated by Django 6.0.3 on 2026-05-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_company_company_flag_company_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joborder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending Review"),
                    ("Open", "Open / Sourcing"),
                    ("Active", "Active"),
                    ("In Progress", "In Progress / Interviewing"),
                    ("Fulfilled", "Fulfilled"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
