# Generated by Django 6.0.3 on 2026-05-09 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_alter_joborder_status"),
        ("core", "0007_companytype_alter_vesseltype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="core.companytype",
            ),
        ),
    ]
