# Generated by Django 6.0.3 on 2026-05-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_alter_company_company_type"),
        ("core", "0008_alter_flag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_flag",
            field=models.ForeignKey(
                blank=True,
                help_text="Country flag / nationality of the company",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies_with_flag",
                to="core.flag",
            ),
        ),
    ]
