# Generated by Django 6.0.3 on 2026-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_alter_company_company_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
