# Generated by Django 6.0.6 on 2026-08-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0017_remap_joborder_status_old_to_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joborder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open / Sourcing"),
                    ("Close", "Closed"),
                    ("Full Filled", "Full Filled"),
                ],
                default="Open",
                max_length=30,
            ),
        ),
    ]
