# Generated by Django 6.0.3

from django.db import migrations

def clear_query_cache(apps, schema_editor):
    try:
        QueryCache = apps.get_model('ai_agents', 'QueryCache')
        QueryCache.objects.all().delete()
    except Exception:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0002_failedquerylog_querycache"),
    ]

    operations = [
        migrations.RunPython(clear_query_cache),
    ]
