# Generated by Django 4.2.23 on 2026-01-21 16:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('QUARANTINE LETTER', 'QUARANTINE LETTER'), ('RUBELLA IMMUNITY', 'RUBELLA IMMUNITY'), ('TESSERA SANITARIA', 'TESSERA SANITARIA'), ('TUBERCULOSIS_LAB_SCREEN', 'Tuberculosis Laboratory Screen'), ('TYPHOID_VACCINATION', 'Typhoid Vaccination'), ('VARICELLA_IMMUNIZATION', 'Varicella Immunization'), ('YELLOW_FEVER_IMMUNIZATION', 'Yellow Fever Immunization'), ('CHICKENPOX_IMMUNITY_SCREENING', 'Chickenpox Immunity Screening'), ('COLOR_VISION_CERTIFICATE', 'Color Vision Certificate'), ('COVID_SARS_VACCINATION', 'COVID-SARS Vaccination'), ('COVID_FORM', 'COVID Form'), ('FOODHANDLER_EXAMS', 'Foodhandler Exams'), ('HEALTH_QUESTIONNAIRE', 'Health Questionnaire'), ('HEPATITIS_A_IMMUNIZATION', 'Hepatitis A Immunization'), ('HEPATITIS_B_IMMUNIZATION', 'Hepatitis B Immunization'), ('ITALIAN_MEDICAL_PRE_EMBARK', 'Italian Medical Pre-Embark Examination'), ('MEASLES_IMMUNITY', 'Measles Immunity'), ('MEDICAL_CERT_SEAFARERS', 'Medical Certificate for Seafarers'), ('MMR_BOOSTER_2', 'MMR Booster 2'), ('MMR_VACC_IMMUNIZATION', 'MMR Vaccination / Immunization'), ('MUMPS_IMMUNITY', 'Mumps Immunity'), ('PERTUSSIS_IMMUNIZATION', 'Pertussis Immunization')], max_length=50)),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_at', models.CharField(blank=True, max_length=255, null=True)),
                ('disease', models.CharField(blank=True, max_length=255, null=True)),
                ('first_date', models.DateField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='vaccinations/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
