# Generated by Django 6.0.1 on 2026-03-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccinations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccination",
            name="name",
            field=models.CharField(
                choices=[
                    ("Quarantine Letter", "Quarantine Letter"),
                    ("Rubella Immunity", "Rubella Immunity"),
                    ("Tessera Sanitaria", "Tessera Sanitaria"),
                    (
                        "Tuberculosis Laboratory Screen",
                        "Tuberculosis Laboratory Screen",
                    ),
                    ("Typhoid Vaccination", "Typhoid Vaccination"),
                    ("Varicella Immunization", "Varicella Immunization"),
                    ("Yellow Fever Immunization", "Yellow Fever Immunization"),
                    ("Chickenpox Immunity Screening", "Chickenpox Immunity Screening"),
                    ("Color Vision Certificate", "Color Vision Certificate"),
                    ("Covid-Sars Vaccination", "Covid-Sars Vaccination"),
                    ("Covid Form", "Covid Form"),
                    ("Foodhandler Exams", "Foodhandler Exams"),
                    ("Health Questionnaire", "Health Questionnaire"),
                    ("Hepatitis A Immunization", "Hepatitis A Immunization"),
                    ("Hepatitis B Immunization", "Hepatitis B Immunization"),
                    (
                        "Italian Medical Pre-Embark Examination",
                        "Italian Medical Pre-Embark Examination",
                    ),
                    ("Measles Immunity", "Measles Immunity"),
                    (
                        "Medical Certificate For Seafarers",
                        "Medical Certificate For Seafarers",
                    ),
                    ("Mmr Booster 2", "Mmr Booster 2"),
                    (
                        "Mmr Vaccination / Immunization",
                        "Mmr Vaccination / Immunization",
                    ),
                    ("Mumps Immunity", "Mumps Immunity"),
                    ("Pertussis Immunization", "Pertussis Immunization"),
                ],
                max_length=100,
            ),
        ),
    ]
