# Generated by Django 6.0.1 on 2026-03-14 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccinations", "0002_alter_vaccination_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccination",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="vaccinations/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
