# Generated by Django 4.2.24 on 2025-09-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_details', models.JSONField(blank=True, default=dict, null=True)),
                ('education', models.JSONField(blank=True, default=dict, null=True)),
                ('contact_details', models.JSONField(blank=True, default=dict, null=True)),
                ('travel_documents', models.JSONField(blank=True, default=dict, null=True)),
                ('professional_qualifications', models.JSONField(blank=True, default=dict, null=True)),
                ('next_of_kin_emergency_contact', models.JSONField(blank=True, default=dict, null=True)),
                ('health_certificates_vaccinations', models.JSONField(blank=True, default=dict, null=True)),
                ('covid_19_vaccination', models.JSONField(blank=True, default=dict, null=True)),
                ('marine_courses', models.JSONField(blank=True, default=dict, null=True)),
                ('sea_service_details', models.JSONField(blank=True, default=dict, null=True)),
                ('specialised_experience', models.JSONField(blank=True, default=dict, null=True)),
                ('references', models.JSONField(blank=True, default=dict, null=True)),
                ('declaration', models.JSONField(blank=True, default=dict, null=True)),
                ('office_use_only', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
