# Generated by Django 4.2.24 on 2025-10-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_document', '0004_remove_applicant_structured_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='assessments',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='competency_tests',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='language_skills',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='medical_history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='physical_measurements',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
