# Generated by Django 4.2.24 on 2025-12-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Prospect', 'Prospect')], default='Active', max_length=20),
        ),
    ]
