# Generated by Django 6.0.1 on 2026-03-14 06:55

import django.core.validators
import licenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0003_alter_userlicense_document_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlicense",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=licenses.models.user_license_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
