# Generated by Django 6.0.3 on 2026-03-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0004_alter_userlicense_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlicense",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userlicense",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
