# Generated by Django 4.2.24 on 2025-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_users_first_name_alter_users_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='marlins_test_issued_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='marlins_test_issued_by',
        ),
        migrations.RemoveField(
            model_name='users',
            name='marlins_test_issued_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='marlins_test_result',
        ),
        migrations.RemoveField(
            model_name='users',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AlterField(
            model_name='users',
            name='college_or_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='marital_status',
            field=models.CharField(default='Single', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='us_visa_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_status',
            field=models.CharField(default='On Site', max_length=40),
        ),
    ]
