# Generated by Django 5.2.8 on 2025-12-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_contract_company_alter_cvsubmission_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Under Review", "Under Review"),
                    ("Interviewed", "Interviewed"),
                    ("Shortlisted", "Shortlisted"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Hired", "Hired"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
