# Generated by Manual Migration on 2026-02-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_users_nationality_alter_users_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='application_position',
            field=models.ForeignKey(blank=True, help_text='Position being applied for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_applicants', to='api.rank'),
        ),
        migrations.AddField(
            model_name='users',
            name='other_position',
            field=models.CharField(blank=True, help_text='Alternative position if any', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='register_code',
            field=models.CharField(blank=True, help_text='Registration code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='register_date',
            field=models.DateField(blank=True, help_text='Registration date', null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_update_date',
            field=models.DateField(blank=True, help_text='Last update date', null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='available_date',
            field=models.DateField(blank=True, help_text='Date when user is available', null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected salary', max_digits=10, null=True),
        ),
    ]
