# Generated by Django 6.0.1 on 2026-02-06 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_users_last_name_users_application_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="certificates",
            field=models.ManyToManyField(
                blank=True, related_name="qualified_users", to="api.certificate"
            ),
        ),
        migrations.CreateModel(
            name="UserCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Name of the certificate/course", max_length=255
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Certificate number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "country_of_issue",
                    models.CharField(
                        blank=True,
                        help_text="Country where issued",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when certificate was issued",
                        null=True,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Date when certificate expires", null=True
                    ),
                ),
                (
                    "issued_by",
                    models.CharField(
                        blank=True,
                        help_text="Issuing authority",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "issued_at",
                    models.CharField(
                        blank=True,
                        help_text="Place of issue",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload certificate document",
                        null=True,
                        upload_to="certificates/",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Certificate", "Certificate"),
                            ("Course", "Marine Course"),
                        ],
                        default="Certificate",
                        help_text="Certificate or Marine Course",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type/name of certificate from predefined list",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.certificate",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated rank if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.rank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Certificate",
                "verbose_name_plural": "User Certificates",
                "ordering": ["-issue_date"],
            },
        ),
    ]
