# Generated by Django 6.0.1 on 2026-02-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_users_certificates_usercertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="management",
            field=models.CharField(
                blank=True,
                help_text="Management level or department",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="Reference number/identifier",
                max_length=50,
                null=True,
            ),
        ),
    ]
