# Generated by Django 6.0.3 on 2026-05-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_clean_user_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="ces_test_file",
            field=models.FileField(blank=True, null=True, upload_to="ces_tests/"),
        ),
        migrations.AddField(
            model_name="users",
            name="ces_test_issued_at",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="ces_test_issued_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="ces_test_issued_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="ces_test_result",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="marlins_test_file",
            field=models.FileField(blank=True, null=True, upload_to="marlins_tests/"),
        ),
        migrations.AddField(
            model_name="users",
            name="other_seaman_book_file",
            field=models.FileField(
                blank=True, null=True, upload_to="other_seaman_books/"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="passport_file",
            field=models.FileField(blank=True, null=True, upload_to="passports/"),
        ),
        migrations.AddField(
            model_name="users",
            name="seaman_book_file",
            field=models.FileField(blank=True, null=True, upload_to="seaman_books/"),
        ),
    ]
