# Generated by Django 5.2.4 on 2025-08-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelingpaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
