# Generated by Django 4.2.23 on 2025-08-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelingpaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
