# <<<<<<< HEAD
# # Generated by Django 5.2.4 on 2025-08-20 19:21
# =======
# # Generated by Django 4.2.23 on 2025-08-24 18:42
# >>>>>>> origin/feature/add-company-and-ship-models

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelingpaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
